export interface ServiceType {
  id: string;
  category: string;
  name: string;
  description: string;
  icon: string;
  estimatedTime: string;
  price: string;
}

export const serviceTypes: ServiceType[] = [
  // Construction Services
  {
    id: "construction-1",
    category: "Construction",
    name: "Residential Construction",
    description: "Build your dream home with expert planning and execution",
    icon: "🏠",
    estimatedTime: "3-6 months",
    price: "₹5,00,000 - ₹50,00,000",
  },
  {
    id: "construction-2",
    category: "Construction",
    name: "Commercial Projects",
    description: "Office buildings, retail spaces, and business complexes",
    icon: "🏢",
    estimatedTime: "6-12 months",
    price: "₹20,00,000 - ₹1 Cr+",
  },
  {
    id: "construction-3",
    category: "Construction",
    name: "Renovations & Repairs",
    description: "Modernize and upgrade your existing space",
    icon: "🔨",
    estimatedTime: "1-3 months",
    price: "₹50,000 - ₹10,00,000",
  },
  {
    id: "construction-4",
    category: "Construction",
    name: "Architectural Design",
    description: "Professional design and planning services",
    icon: "📐",
    estimatedTime: "2-4 weeks",
    price: "₹25,000 - ₹2,00,000",
  },

// Electronics Services
  
  {
    id: "electronics-1",
    category: "Electronics",
    name: "Customized Touch Switch Boards",
    description: "Modern touch-based switch boards with custom design and installation",
    icon: "🎛️",
    estimatedTime: "1-2 days",
    price: "₹3,000 - ₹25,000",
  },
  {
    id: "electronics-2",
    category: "Electronics",
    name: "Water Level Controllers",
    description: "Automatic water level control systems for tanks and motors",
    icon: "💧",
    estimatedTime: "2-5 hours",
    price: "₹2,000 - ₹15,000",
  },
  {
    id: "electronics-3",
    category: "Electronics",
    name: "Gate Automation",
    description: "Automatic gate systems with remote and sensor control",
    icon: "🚧",
    estimatedTime: "1-3 days",
    price: "₹15,000 - ₹1,50,000",
  },
  {
    id: "electronics-4",
    category: "Electronics",
    name: "Motor Controllers",
    description: "Installation and servicing of motor control systems",
    icon: "⚙️",
    estimatedTime: "3-6 hours",
    price: "₹3,000 - ₹30,000",
  },
  {
  id: "electronics-5",
  category: "Electronics",
  name: "Electronics & Robotics Projects",
  description: "Custom electronics and robotics solutions for students, automation, and industrial needs",
  icon: "🤖",
  estimatedTime: "3 days - 4 weeks",
  price: "₹5,000 - ₹2,50,000",
},{
  id: "electronics-6",
  category: "Electronics",
  name: "Student Projects (Electronics/Robotics)",
  description: "Final year and mini projects with documentation and support",
  icon: "🎓",
  estimatedTime: "1-3 weeks",
  price: "₹3,000 - ₹50,000",
},
{
  id: "electronics-7",
  category: "Electronics",
  name: "Automation Projects",
  description: "Home and industrial automation using IoT and controllers",
  icon: "🏠",
  estimatedTime: "1-4 weeks",
  price: "₹10,000 - ₹2,00,000",
},
{
  id: "electronics-8",
  category: "Electronics",
  name: "Computer & Laptop Sales/Service",
  description: "Sales, repair, upgrades, and maintenance of computers and laptops",
  icon: "💻",
  estimatedTime: "2-6 hours",
  price: "₹1,000 - ₹1,00,000",
},
{
  id: "electronics-9",
  category: "Electronics",
  name: "Printer Service & Sales",
  description: "Printer installation, repair, cartridge refilling, and sales",
  icon: "🖨️",
  estimatedTime: "1-3 hours",
  price: "₹500 - ₹25,000",
},
{
  id: "electronics-10",
  category: "Electronics",
  name: "CCTV Installation & Support",
  description: "Complete CCTV setup, maintenance, and surveillance solutions",
  icon: "📷",
  estimatedTime: "1-2 days",
  price: "₹5,000 - ₹1,50,000",
},


  // Education Services
  {
    id: "education-1",
    category: "Education",
    name: "Mathematics Tutoring",
    description: "Expert guidance in Math for all grades",
    icon: "📊",
    estimatedTime: "1-2 hours/session",
    price: "₹200 - ₹1,000/hour",
  },
  {
    id: "education-2",
    category: "Education",
    name: "Science Coaching",
    description: "Physics, Chemistry, Biology explained simply",
    icon: "🔬",
    estimatedTime: "1-2 hours/session",
    price: "₹200 - ₹1,000/hour",
  },
  {
    id: "education-3",
    category: "Education",
    name: "Language Classes",
    description: "English, Tamil, Hindi, and other languages",
    icon: "📚",
    estimatedTime: "1 hour/session",
    price: "₹150 - ₹800/hour",
  },
  {
    id: "education-4",
    category: "Education",
    name: "Competitive Exam Prep",
    description: "Prepare for JEE, NEET, UPSC, and other exams",
    icon: "🎯",
    estimatedTime: "2-3 hours/session",
    price: "₹500 - ₹2,000/hour",
  },

  // CCTV & Networking Services
  {
    id: "cctv-1",
    category: "CCTV & Networking",
    name: "CCTV Installation",
    description: "Professional camera setup for home and office security",
    icon: "📹",
    estimatedTime: "4-8 hours",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "cctv-2",
    category: "CCTV & Networking",
    name: "Network Setup",
    description: "WiFi installation and network configuration",
    icon: "🌐",
    estimatedTime: "2-4 hours",
    price: "₹2,000 - ₹15,000",
  },
  {
    id: "cctv-3",
    category: "CCTV & Networking",
    name: "Security Monitoring",
    description: "24/7 monitoring service with alert system",
    icon: "🔒",
    estimatedTime: "Ongoing",
    price: "₹1,000 - ₹5,000/month",
  },
  {
    id: "cctv-4",
    category: "CCTV & Networking",
    name: "Maintenance Service",
    description: "Regular maintenance and system updates",
    icon: "⚙️",
    estimatedTime: "1-2 hours",
    price: "₹500 - ₹2,000",
  },
{
  id: "cctv-5",
  category: "CCTV & Networking",
  name: "CCTV Service & Networking Solutions",
  description: "Complete CCTV servicing and advanced networking solutions including setup, troubleshooting, and optimization",
  icon: "📡",
  estimatedTime: "2-6 hours",
  price: "₹2,000 - ₹25,000",
},
  // Furniture Services
  {
    id: "furniture-1",
    category: "Furniture",
    name: "Custom Furniture",
    description: "Made-to-order furniture for your needs",
    icon: "🛋️",
    estimatedTime: "2-4 weeks",
    price: "₹10,000 - ₹5,00,000",
  },
  {
    id: "furniture-2",
    category: "Furniture",
    name: "Interior Design",
    description: "Professional design consultation for your space",
    icon: "🎨",
    estimatedTime: "1-2 weeks",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "furniture-3",
    category: "Furniture",
    name: "Installation Service",
    description: "Professional assembly and installation",
    icon: "🔩",
    estimatedTime: "2-4 hours",
    price: "₹2,000 - ₹10,000",
  },
  {
    id: "furniture-4",
    category: "Furniture",
    name: "Home Delivery",
    description: "Quick and safe delivery to your doorstep",
    icon: "🚚",
    estimatedTime: "1-3 days",
    price: "₹500 - ₹5,000",
  },

  // Technology Services
  {
    id: "tech-1",
    category: "Technology",
    name: "Web Development",
    description: "Custom website development and design",
    icon: "🌐",
    estimatedTime: "4-12 weeks",
    price: "₹50,000 - ₹10,00,000",
  },
  {
    id: "tech-2",
    category: "Technology",
    name: "Mobile App Development",
    description: "iOS and Android app development",
    icon: "📲",
    estimatedTime: "8-16 weeks",
    price: "₹1,00,000 - ₹20,00,000",
  },
  {
    id: "tech-3",
    category: "Technology",
    name: "Software Development",
    description: "Custom software solutions for businesses",
    icon: "💾",
    estimatedTime: "Varies",
    price: "₹2,00,000 - ₹50,00,000",
  },
  {
    id: "tech-4",
    category: "Technology",
    name: "IT Consulting",
    description: "Technology strategy and implementation",
    icon: "🤝",
    estimatedTime: "Ongoing",
    price: "₹5,000 - ₹50,000/day",
  },

  // Fabrication Services
  {
    id: "fabrication-1",
    category: "Fabrication",
    name: "Metal Gates & Railings",
    description: "Custom metal designs for security and style",
    icon: "🚪",
    estimatedTime: "1-2 weeks",
    price: "₹10,000 - ₹1,00,000",
  },
  {
    id: "fabrication-2",
    category: "Fabrication",
    name: "Welding Work",
    description: "Professional welding and metal joining",
    icon: "🔥",
    estimatedTime: "1-3 days",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "fabrication-3",
    category: "Fabrication",
    name: "Custom Designs",
    description: "Bespoke metal fabrication projects",
    icon: "✨",
    estimatedTime: "Varies",
    price: "₹20,000 - ₹5,00,000",
  },
  {
    id: "fabrication-4",
    category: "Fabrication",
    name: "Installation & Repair",
    description: "Installation and repair of metal structures",
    icon: "🔧",
    estimatedTime: "1-2 days",
    price: "₹5,000 - ₹30,000",
  },

  // ✅ New Services Added
  {
    id: "fabrication-5",
    category: "Fabrication",
    name: "UPVC Windows & Doors",
    description: "Durable, weather-resistant UPVC window and door solutions",
    icon: "🪟",
    estimatedTime: "3-7 days",
    price: "₹15,000 - ₹2,00,000",
  },
  {
    id: "fabrication-6",
    category: "Fabrication",
    name: "Mosquito Net Windows",
    description: "Protective mesh installation for windows to keep insects out",
    icon: "🦟",
    estimatedTime: "1-2 days",
    price: "₹2,000 - ₹20,000",
  },
  {
    id: "fabrication-7",
    category: "Fabrication",
    name: "General Fabrication Works",
    description: "All types of custom fabrication and structural work",
    icon: "🏗️",
    estimatedTime: "Varies",
    price: "₹10,000 - ₹3,00,000",
  },
];

export function getServicesByCategory(category: string): ServiceType[] {
  return serviceTypes.filter((service) => service.category === category);
}
