export interface ServiceType {
  id: string;
  category: string;
  name: string;
  description: string;
  keywords: string[];
  icon: string;
  estimatedTime: string;
  price: string;
}

export const serviceTypes: ServiceType[] = [
  // Construction Services
  {
    id: "construction-1",
    category: "Construction",
    name: "Building Construction",
    description: "Complete residential and commercial building construction services",
    keywords: ["building", "construction", "residential", "commercial", "house", "home", "contractor", "civil", "structure", "new build"],
    icon: "🏗️",
    estimatedTime: "3-12 months",
    price: "₹5,00,000 - ₹1 Cr+",
  },
  {
    id: "construction-2",
    category: "Construction",
    name: "Interior Renovation",
    description: "Transform your interiors with modern renovation and design solutions",
    keywords: ["interior", "renovation", "remodel", "design", "makeover", "upgrade", "room", "office", "modern", "decoration"],
    icon: "🛋️",
    estimatedTime: "2-8 weeks",
    price: "₹50,000 - ₹15,00,000",
  },
  {
    id: "construction-3",
    category: "Construction",
    name: "Roof Sheet Work",
    description: "Durable and weather-resistant roofing sheet installation services",
    keywords: ["roof", "roofing", "sheet", "terrace", "waterproof", "weather", "covering", "shed", "metal sheet", "rooftop"],
    icon: "🏠",
    estimatedTime: "3-10 days",
    price: "₹20,000 - ₹5,00,000",
  },
  {
    id: "construction-4",
    category: "Construction",
    name: "Painting Services",
    description: "Professional interior and exterior painting for homes and offices",
    keywords: ["painting", "paint", "wall", "interior", "exterior", "colour", "color", "brush", "coat", "home painting"],
    icon: "🎨",
    estimatedTime: "2-7 days",
    price: "₹10,000 - ₹2,00,000",
  },
  {
    id: "construction-5",
    category: "Construction",
    name: "UPVC Windows & Doors",
    description: "High-quality UPVC window and door installation with modern finish",
    keywords: ["upvc", "window", "door", "glass", "frame", "fitting", "sliding", "casement", "soundproof", "installation"],
    icon: "🪟",
    estimatedTime: "5-15 days",
    price: "₹30,000 - ₹5,00,000",
  },
  {
    id: "construction-6",
    category: "Construction",
    name: "Modular Kitchen & Wardrobes",
    description: "Custom plywood modular kitchens and wardrobes with premium design",
    keywords: ["modular", "kitchen", "wardrobe", "cabinet", "cupboard", "plywood", "storage", "custom", "furniture", "fitting"],
    icon: "🧰",
    estimatedTime: "2-6 weeks",
    price: "₹80,000 - ₹10,00,000",
  },

  // Electronics Services
  {
    id: "electronics-1",
    category: "Electronics",
    name: "Customized Touch Switch Boards",
    description: "Modern touch-based switch boards with custom design and installation",
    keywords: ["touch", "switch", "switchboard", "panel", "smart", "electrical", "board", "custom", "wiring", "modular"],
    icon: "🎛️",
    estimatedTime: "1-2 days",
    price: "₹3,000 - ₹25,000",
  },
  {
    id: "electronics-2",
    category: "Electronics",
    name: "Water Level Controllers",
    description: "Automatic water level control systems for tanks and motors",
    keywords: ["water", "level", "controller", "tank", "motor", "automatic", "sensor", "pump", "overflow", "float"],
    icon: "💧",
    estimatedTime: "2-5 hours",
    price: "₹2,000 - ₹15,000",
  },
  {
    id: "electronics-3",
    category: "Electronics",
    name: "Gate Automation",
    description: "Automatic gate systems with remote and sensor control",
    keywords: ["gate", "automatic", "automation", "remote", "sensor", "sliding gate", "motor", "access", "control", "door automation"],
    icon: "🚧",
    estimatedTime: "1-3 days",
    price: "₹15,000 - ₹1,50,000",
  },
  {
    id: "electronics-4",
    category: "Electronics",
    name: "Motor Controllers",
    description: "Installation and servicing of motor control systems",
    keywords: ["motor", "controller", "drive", "pump", "speed", "control", "industrial", "service", "starter", "electrical"],
    icon: "⚙️",
    estimatedTime: "3-6 hours",
    price: "₹3,000 - ₹30,000",
  },
  {
    id: "electronics-5",
    category: "Electronics",
    name: "Electronics & Robotics Projects",
    description: "Custom electronics and robotics solutions for students, automation, and industrial needs",
    keywords: ["electronics", "robotics", "project", "automation", "circuit", "arduino", "raspberry pi", "IoT", "custom", "industrial"],
    icon: "🤖",
    estimatedTime: "3 days - 4 weeks",
    price: "₹5,000 - ₹2,50,000",
  },
  {
    id: "electronics-6",
    category: "Electronics",
    name: "Student Projects (Electronics/Robotics)",
    description: "Final year and mini projects with documentation and support",
    keywords: ["student", "project", "final year", "mini project", "college", "engineering", "electronics", "robotics", "documentation", "support"],
    icon: "🎓",
    estimatedTime: "1-3 weeks",
    price: "₹3,000 - ₹50,000",
  },
  {
    id: "electronics-7",
    category: "Electronics",
    name: "Automation Projects",
    description: "Home and industrial automation using IoT and controllers",
    keywords: ["automation", "home automation", "IoT", "smart home", "industrial", "controller", "sensor", "remote", "wireless", "smart"],
    icon: "🏠",
    estimatedTime: "1-4 weeks",
    price: "₹10,000 - ₹2,00,000",
  },
  {
    id: "electronics-8",
    category: "Electronics",
    name: "Computer & Laptop Sales/Service",
    description: "Sales, repair, upgrades, and maintenance of computers and laptops",
    keywords: ["computer", "laptop", "PC", "repair", "service", "sales", "upgrade", "hardware", "software", "maintenance"],
    icon: "💻",
    estimatedTime: "2-6 hours",
    price: "₹1,000 - ₹1,00,000",
  },
  {
    id: "electronics-9",
    category: "Electronics",
    name: "Printer Service & Sales",
    description: "Printer installation, repair, cartridge refilling, and sales",
    keywords: ["printer", "print", "cartridge", "ink", "refill", "repair", "sales", "inkjet", "laser", "toner"],
    icon: "🖨️",
    estimatedTime: "1-3 hours",
    price: "₹500 - ₹25,000",
  },
  {
    id: "electronics-10",
    category: "Electronics",
    name: "CCTV Installation & Support",
    description: "Complete CCTV setup, maintenance, and surveillance solutions",
    keywords: ["cctv", "camera", "security", "surveillance", "installation", "support", "DVR", "NVR", "IP camera", "monitoring"],
    icon: "📷",
    estimatedTime: "1-2 days",
    price: "₹5,000 - ₹1,50,000",
  },

  // Education Services
  {
    id: "education-1",
    name: "Spoken Hindi Academy",
    category: "Education",
    description: "Raanuva Veeran Spoken Hindi Academy providing spoken Hindi coaching",
    keywords: ["hindi", "spoken hindi", "language", "class", "academy", "coaching", "communication", "course", "training", "fluency"],
    icon: "🎯",
    estimatedTime: "2-3 hours/session",
    price: "₹500 - ₹2,000/hour",
  },
  {
    id: "education-2",
    name: "Basic Hindi Learning",
    category: "Education",
    description: "Learn Hindi basics including reading, writing, and simple conversation",
    keywords: ["hindi", "basic", "beginner", "reading", "writing", "conversation", "learn", "language", "class", "foundation"],
    icon: "📖",
    estimatedTime: "1-2 hours/session",
    price: "₹300 - ₹1,000/hour",
  },
  {
    id: "education-3",
    name: "Advanced Hindi Speaking",
    category: "Education",
    description: "Improve fluency, pronunciation, and advanced communication in Hindi",
    keywords: ["hindi", "advanced", "fluency", "pronunciation", "speaking", "communication", "language", "class", "coaching", "expert"],
    icon: "🗣️",
    estimatedTime: "1-2 hours/session",
    price: "₹500 - ₹1,500/hour",
  },
  {
    id: "education-4",
    name: "Hindi Writing & Grammar",
    category: "Education",
    description: "Focus on Hindi grammar, sentence formation, and writing skills",
    keywords: ["hindi", "grammar", "writing", "sentence", "formation", "skill", "language", "class", "coaching", "composition"],
    icon: "✍️",
    estimatedTime: "1-2 hours/session",
    price: "₹400 - ₹1,200/hour",
  },

  // CCTV & Networking Services
  {
    id: "cctv-1",
    category: "CCTV & Networking",
    name: "CCTV Installation",
    description: "Professional camera setup for home and office security",
    keywords: ["cctv", "camera", "security", "installation", "surveillance", "DVR", "NVR", "home security", "office", "monitoring"],
    icon: "📹",
    estimatedTime: "4-8 hours",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "cctv-2",
    category: "CCTV & Networking",
    name: "Network Setup",
    description: "WiFi installation and network configuration",
    keywords: ["network", "wifi", "internet", "router", "setup", "configuration", "LAN", "wireless", "broadband", "connectivity"],
    icon: "🌐",
    estimatedTime: "2-4 hours",
    price: "₹2,000 - ₹15,000",
  },
  {
    id: "cctv-3",
    category: "CCTV & Networking",
    name: "Security Monitoring",
    description: "24/7 monitoring service with alert system",
    keywords: ["monitoring", "security", "surveillance", "alert", "24/7", "watch", "remote", "live", "protection", "AMC"],
    icon: "🔒",
    estimatedTime: "Ongoing",
    price: "₹1,000 - ₹5,000/month",
  },
  {
    id: "cctv-4",
    category: "CCTV & Networking",
    name: "Maintenance Service",
    description: "Regular maintenance and system updates",
    keywords: ["maintenance", "service", "repair", "update", "check", "AMC", "annual", "upkeep", "support", "troubleshoot"],
    icon: "⚙️",
    estimatedTime: "1-2 hours",
    price: "₹500 - ₹2,000",
  },

  // Furniture Services
  {
    id: "furniture-1",
    category: "Furniture",
    name: "Custom Furniture",
    description: "Made-to-order furniture for your needs",
    keywords: ["furniture", "custom", "made to order", "sofa", "table", "chair", "bed", "wooden", "design", "crafted"],
    icon: "🛋️",
    estimatedTime: "2-4 weeks",
    price: "₹10,000 - ₹5,00,000",
  },
  {
    id: "furniture-2",
    category: "Furniture",
    name: "Interior Design",
    description: "Professional design consultation for your space",
    keywords: ["interior", "design", "consultation", "decor", "space", "planning", "layout", "aesthetic", "furnishing", "style"],
    icon: "🎨",
    estimatedTime: "1-2 weeks",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "furniture-3",
    category: "Furniture",
    name: "Installation Service",
    description: "Professional assembly and installation",
    keywords: ["installation", "assembly", "fitting", "setup", "mount", "fix", "furniture", "service", "professional", "home"],
    icon: "🔩",
    estimatedTime: "2-4 hours",
    price: "₹2,000 - ₹10,000",
  },
  {
    id: "furniture-4",
    category: "Furniture",
    name: "Home Delivery",
    description: "Quick and safe delivery to your doorstep",
    keywords: ["delivery", "home delivery", "transport", "shipping", "doorstep", "logistics", "safe", "quick", "furniture", "drop"],
    icon: "🚚",
    estimatedTime: "1-3 days",
    price: "₹500 - ₹5,000",
  },
  {
    id: "furniture-5",
    category: "Furniture",
    name: "Tile Installation",
    description: "Professional tile installation for residential and commercial spaces",
    keywords: ["tile", "tiling", "flooring", "floor", "wall tile", "ceramic", "vitrified", "installation", "bathroom", "kitchen"],
    icon: "🧱",
    estimatedTime: "1-3 days",
    price: "₹2,000 - ₹15,000",
  },

  // Technology Services
  {
    id: "tech-1",
    category: "Technology",
    name: "Web Development",
    description: "Custom website development and design",
    keywords: ["web", "website", "development", "design", "HTML", "react", "frontend", "backend", "custom", "online"],
    icon: "🌐",
    estimatedTime: "4-12 weeks",
    price: "₹50,000 - ₹10,00,000",
  },
  {
    id: "tech-2",
    category: "Technology",
    name: "Mobile App Development",
    description: "iOS and Android app development",
    keywords: ["mobile", "app", "iOS", "android", "development", "application", "flutter", "react native", "smartphone", "software"],
    icon: "📲",
    estimatedTime: "8-16 weeks",
    price: "₹1,00,000 - ₹20,00,000",
  },
  {
    id: "tech-3",
    category: "Technology",
    name: "Software Development",
    description: "Custom software solutions for businesses",
    keywords: ["software", "development", "custom", "business", "application", "coding", "programming", "solution", "enterprise", "system"],
    icon: "💾",
    estimatedTime: "Varies",
    price: "₹2,00,000 - ₹50,00,000",
  },
  {
    id: "tech-4",
    category: "Technology",
    name: "IT Consulting",
    description: "Technology strategy and implementation",
    keywords: ["IT", "consulting", "technology", "strategy", "implementation", "advice", "digital", "transformation", "infrastructure", "expert"],
    icon: "🤝",
    estimatedTime: "Ongoing",
    price: "₹5,000 - ₹50,000/day",
  },

  // Fabrication Services
  {
    id: "fabrication-1",
    category: "Fabrication",
    name: "UPVC Windows & Doors",
    description: "High-quality UPVC window and door installation with modern finish and durability",
    keywords: ["upvc", "window", "door", "frame", "glass", "fitting", "sliding", "fabrication", "durable", "modern"],
    icon: "🪟",
    estimatedTime: "3-10 days",
    price: "₹15,000 - ₹3,00,000",
  },
  {
    id: "fabrication-2",
    category: "Fabrication",
    name: "Mosquito Net Windows",
    description: "Custom-fit mosquito mesh solutions for windows and doors to keep insects out",
    keywords: ["mosquito", "net", "mesh", "window", "door", "insect", "protection", "custom", "screen", "fitting"],
    icon: "🦟",
    estimatedTime: "1-3 days",
    price: "₹2,000 - ₹25,000",
  },
  {
    id: "fabrication-3",
    category: "Fabrication",
    name: "Fabrication Works",
    description: "All types of metal fabrication including gates, grills, railings, and custom structures",
    keywords: ["fabrication", "metal", "gate", "grill", "railing", "steel", "iron", "welding", "custom", "structure"],
    icon: "🏗️",
    estimatedTime: "3-15 days",
    price: "₹10,000 - ₹5,00,000",
  },
];

export function getServicesByCategory(category: string): ServiceType[] {
  return serviceTypes.filter((service) => service.category === category);
}