import { ServiceType } from "./service-types";

export const serviceTypesTa: ServiceType[] = [
  // Construction Services
  {
    id: "construction-1",
    category: "Construction",
    name: "கட்டிடக் கட்டுமானம்",
    description: "முழுமையான குடியிருப்பு மற்றும் வணிக கட்டிடக் கட்டுமான சேவைகள்",
    keywords: ["building", "construction", "residential", "commercial", "house", "home", "contractor", "civil", "structure", "new build"],
    icon: "🏗️",
    estimatedTime: "3-12 மாதங்கள்",
    price: "₹5,00,000 - ₹1 கோடி+",
  },
  {
    id: "construction-2",
    category: "Construction",
    name: "உட்புறப் புதுப்பித்தல்",
    description: "நவீன புதுப்பித்தல் மற்றும் வடிவமைப்புத் தீர்வுகளுடன் உங்கள் உட்புறங்களை மாற்றவும்",
    keywords: ["interior", "renovation", "remodel", "design", "makeover", "upgrade", "room", "office", "modern", "decoration"],
    icon: "🛋️",
    estimatedTime: "2-8 வாரங்கள்",
    price: "₹50,000 - ₹15,00,000",
  },
  {
    id: "construction-3",
    category: "Construction",
    name: "கூரைத் தகடு வேலை",
    description: "நீடித்த மற்றும் வானிலையைத் தாங்கும் கூரைத் தகடு பொருத்துதல் சேவைகள்",
    keywords: ["roof", "roofing", "sheet", "terrace", "waterproof", "weather", "covering", "shed", "metal sheet", "rooftop"],
    icon: "🏠",
    estimatedTime: "3-10 நாட்கள்",
    price: "₹20,000 - ₹5,00,000",
  },
  {
    id: "construction-4",
    category: "Construction",
    name: "பெயிண்டிங் சேவைகள்",
    description: "வீடுகள் மற்றும் அலுவலகங்களுக்குத் தொழில்முறையான உட்புற மற்றும் வெளிப்புற பெயிண்டிங்",
    keywords: ["painting", "paint", "wall", "interior", "exterior", "colour", "color", "brush", "coat", "home painting"],
    icon: "🎨",
    estimatedTime: "2-7 நாட்கள்",
    price: "₹10,000 - ₹2,00,000",
  },
  {
    id: "construction-5",
    category: "Construction",
    name: "UPVC ஜன்னல்கள் & கதவுகள்",
    description: "நவீன தோற்றத்துடன் உயர் தரமான UPVC ஜன்னல் மற்றும் கதவுப் பொருத்துதல்",
    keywords: ["upvc", "window", "door", "glass", "frame", "fitting", "sliding", "casement", "soundproof", "installation"],
    icon: "🪟",
    estimatedTime: "5-15 நாட்கள்",
    price: "₹30,000 - ₹5,00,000",
  },
  {
    id: "construction-6",
    category: "Construction",
    name: "மாடுலர் கிச்சன் & அலமாரிகள்",
    description: "ப்ரீமியம் வடிவமைப்புடன் தனிப்பயன் பிளைவுட் மாடுலர் கிச்சன்கள் மற்றும் அலமாரிகள்",
    keywords: ["modular", "kitchen", "wardrobe", "cabinet", "cupboard", "plywood", "storage", "custom", "furniture", "fitting"],
    icon: "🧰",
    estimatedTime: "2-6 வாரங்கள்",
    price: "₹80,000 - ₹10,00,000",
  },

  // Electronics Services
  {
    id: "electronics-1",
    category: "Electronics",
    name: "தனிப்பயனாக்கப்பட்ட டச் சுவிட்ச் போர்டுகள்",
    description: "தனிப்பயன் வடிவமைப்பு மற்றும் பொருத்துதலுடன் நவீன டச்-அடிப்படையிலான சுவிட்ச் போர்டுகள்",
    keywords: ["touch", "switch", "switchboard", "panel", "smart", "electrical", "board", "custom", "wiring", "modular"],
    icon: "🎛️",
    estimatedTime: "1-2 நாட்கள்",
    price: "₹3,000 - ₹25,000",
  },
  {
    id: "electronics-2",
    category: "Electronics",
    name: "நீர் மட்டக் கட்டுப்பாட்டாளர்கள்",
    description: "தொட்டிகள் மற்றும் மோட்டார்களுக்கான தானியங்கி நீர் மட்டக் கட்டுப்பாட்டு அமைப்புகள்",
    keywords: ["water", "level", "controller", "tank", "motor", "automatic", "sensor", "pump", "overflow", "float"],
    icon: "💧",
    estimatedTime: "2-5 மணிநேரம்",
    price: "₹2,000 - ₹15,000",
  },
  {
    id: "electronics-3",
    category: "Electronics",
    name: "கேட் ஆட்டோமேஷன்",
    description: "ரிமோட் மற்றும் சென்சார் கட்டுப்பாட்டுடன் தானியங்கி கேட் அமைப்புகள்",
    keywords: ["gate", "automatic", "automation", "remote", "sensor", "sliding gate", "motor", "access", "control", "door automation"],
    icon: "🚧",
    estimatedTime: "1-3 நாட்கள்",
    price: "₹15,000 - ₹1,50,000",
  },
  {
    id: "electronics-4",
    category: "Electronics",
    name: "மோட்டார் கட்டுப்பாட்டாளர்கள்",
    description: "மோட்டார் கட்டுப்பாட்டு அமைப்புகளை நிறுவுதல் மற்றும் சேவை செய்தல்",
    keywords: ["motor", "controller", "drive", "pump", "speed", "control", "industrial", "service", "starter", "electrical"],
    icon: "⚙️",
    estimatedTime: "3-6 மணிநேரம்",
    price: "₹3,000 - ₹30,000",
  },
  {
    id: "electronics-5",
    category: "Electronics",
    name: "எலக்ட்ரானிக்ஸ் & ரோபாட்டிக்ஸ் திட்டங்கள்",
    description: "மாணவர்கள், ஆட்டோமேஷன் மற்றும் தொழில்துறைத் தேவைகளுக்கான தனிப்பயன் எலக்ட்ரானிக்ஸ் மற்றும் ரோபாட்டிக்ஸ் தீர்வுகள்",
    keywords: ["electronics", "robotics", "project", "automation", "circuit", "arduino", "raspberry pi", "IoT", "custom", "industrial"],
    icon: "🤖",
    estimatedTime: "3 நாட்கள் - 4 வாரங்கள்",
    price: "₹5,000 - ₹2,50,000",
  },
  {
    id: "electronics-6",
    category: "Electronics",
    name: "மாணவர் திட்டங்கள் (எலக்ட்ரானிக்ஸ்/ரோபாட்டிக்ஸ்)",
    description: "ஆவணம் மற்றும் ஆதரவுடன் இறுதியாண்டு மற்றும் சிறிய திட்டங்கள்",
    keywords: ["student", "project", "final year", "mini project", "college", "engineering", "electronics", "robotics", "documentation", "support"],
    icon: "🎓",
    estimatedTime: "1-3 வாரங்கள்",
    price: "₹3,000 - ₹50,000",
  },
  {
    id: "electronics-7",
    category: "Electronics",
    name: "ஆட்டோமேஷன் திட்டங்கள்",
    description: "IoT மற்றும் கட்டுப்பாட்டாளர்களைப் பயன்படுத்தும் வீடு மற்றும் தொழில்துறை ஆட்டோமேஷன்",
    keywords: ["automation", "home automation", "IoT", "smart home", "industrial", "controller", "sensor", "remote", "wireless", "smart"],
    icon: "🏠",
    estimatedTime: "1-4 வாரங்கள்",
    price: "₹10,000 - ₹2,00,000",
  },
  {
    id: "electronics-8",
    category: "Electronics",
    name: "கணினி & லேப்டாப் விற்பனை/சேவை",
    description: "கணினிகள் மற்றும் லேப்டாப்களின் விற்பனை, பழுதுபார்த்தல், மேம்படுத்துதல் மற்றும் பராமரிப்பு",
    keywords: ["computer", "laptop", "PC", "repair", "service", "sales", "upgrade", "hardware", "software", "maintenance"],
    icon: "💻",
    estimatedTime: "2-6 மணிநேரம்",
    price: "₹1,000 - ₹1,00,000",
  },
  {
    id: "electronics-9",
    category: "Electronics",
    name: "பிரிண்டர் சேவை & விற்பனை",
    description: "பிரிண்டர் நிறுவுதல், பழுதுபார்த்தல், கார்ட்ரிட்ஜ் நிரப்புதல் மற்றும் விற்பனை",
    keywords: ["printer", "print", "cartridge", "ink", "refill", "repair", "sales", "inkjet", "laser", "toner"],
    icon: "🖨️",
    estimatedTime: "1-3 மணிநேரம்",
    price: "₹500 - ₹25,000",
  },
  {
    id: "electronics-10",
    category: "Electronics",
    name: "சிசிடிவி பொருத்துதல் & ஆதரவு",
    description: "முழுமையான சிசிடிவி அமைப்பு, பராமரிப்பு மற்றும் கண்காணிப்புத் தீர்வுகள்",
    keywords: ["cctv", "camera", "security", "surveillance", "installation", "support", "DVR", "NVR", "IP camera", "monitoring"],
    icon: "📷",
    estimatedTime: "1-2 நாட்கள்",
    price: "₹5,000 - ₹1,50,000",
  },

  // Education Services
  {
    id: "education-1",
    name: "ஸ்போக்கன் ஹிந்தி அகாடமி",
    category: "Education",
    description: "ராணுவ வீரன் ஸ்போக்கன் ஹிந்தி அகாடமி பேசும் ஹிந்திப் பயிற்சியை வழங்குகிறது",
    keywords: ["hindi", "spoken hindi", "language", "class", "academy", "coaching", "communication", "course", "training", "fluency"],
    icon: "🎯",
    estimatedTime: "2-3 மணிநேரம்/அமர்வு",
    price: "₹500 - ₹2,000/மணிநேரம்",
  },
  {
    id: "education-2",
    name: "அடிப்படை ஹிந்தி கற்றல்",
    category: "Education",
    description: "படித்தல், எழுதுதல் மற்றும் எளிய உரையாடல் உட்பட ஹிந்தி அடிப்படைகளைக் கற்கவும்",
    keywords: ["hindi", "basic", "beginner", "reading", "writing", "conversation", "learn", "language", "class", "foundation"],
    icon: "📖",
    estimatedTime: "1-2 மணிநேரம்/அமர்வு",
    price: "₹300 - ₹1,000/மணிநேரம்",
  },
  {
    id: "education-3",
    name: "உயர்தர ஹிந்திப் பேச்சு",
    category: "Education",
    description: "ஹிந்தியில் சரளத்தன்மை, உச்சரிப்பு மற்றும் உயர்தரத் தொடர்பை மேம்படுத்தவும்",
    keywords: ["hindi", "advanced", "fluency", "pronunciation", "speaking", "communication", "language", "class", "coaching", "expert"],
    icon: "🗣️",
    estimatedTime: "1-2 மணிநேரம்/அமர்வு",
    price: "₹500 - ₹1,500/மணிநேரம்",
  },
  {
    id: "education-4",
    name: "ஹிந்தி எழுதுதல் & இலக்கணம்",
    category: "Education",
    description: "ஹிந்தி இலக்கணம், வாக்கிய அமைப்பு மற்றும் எழுதும் திறன்களில் கவனம் செலுத்துங்கள்",
    keywords: ["hindi", "grammar", "writing", "sentence", "formation", "skill", "language", "class", "coaching", "composition"],
    icon: "✍️",
    estimatedTime: "1-2 மணிநேரம்/அமர்வு",
    price: "₹400 - ₹1,200/மணிநேரம்",
  },

  // CCTV & Networking Services
  {
    id: "cctv-1",
    category: "CCTV & Networking",
    name: "சிசிடிவி பொருத்துதல்",
    description: "வீடு மற்றும் அலுவலகப் பாதுகாப்பிற்கான தொழில்முறையான கேமரா அமைப்பு",
    keywords: ["cctv", "camera", "security", "installation", "surveillance", "DVR", "NVR", "home security", "office", "monitoring"],
    icon: "📹",
    estimatedTime: "4-8 மணிநேரம்",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "cctv-2",
    category: "CCTV & Networking",
    name: "நெட்வொர்க் அமைத்தல்",
    description: "வைஃபை நிறுவுதல் மற்றும் நெட்வொர்க் கட்டமைப்பு",
    keywords: ["network", "wifi", "internet", "router", "setup", "configuration", "LAN", "wireless", "broadband", "connectivity"],
    icon: "🌐",
    estimatedTime: "2-4 மணிநேரம்",
    price: "₹2,000 - ₹15,000",
  },
  {
    id: "cctv-3",
    category: "CCTV & Networking",
    name: "பாதுகாப்புக் கண்காணிப்பு",
    description: "எச்சரிக்கை அமைப்புடன் 24/7 கண்காணிப்புச் சேவை",
    keywords: ["monitoring", "security", "surveillance", "alert", "24/7", "watch", "remote", "live", "protection", "AMC"],
    icon: "🔒",
    estimatedTime: "தொடரும்",
    price: "₹1,000 - ₹5,000/மாதம்",
  },
  {
    id: "cctv-4",
    category: "CCTV & Networking",
    name: "பராமரிப்பு சேவை",
    description: "வழக்கமான பராமரிப்பு மற்றும் அமைப்புப் புதுப்பிப்புகள்",
    keywords: ["maintenance", "service", "repair", "update", "check", "AMC", "annual", "upkeep", "support", "troubleshoot"],
    icon: "⚙️",
    estimatedTime: "1-2 மணிநேரம்",
    price: "₹500 - ₹2,000",
  },

  // Furniture Services
  {
    id: "furniture-1",
    category: "Furniture",
    name: "தனிப்பயன் பர்னிச்சர்",
    description: "உங்கள் தேவைகளுக்கான ஆர்டர்-செய்த பர்னிச்சர்",
    keywords: ["furniture", "custom", "made to order", "sofa", "table", "chair", "bed", "wooden", "design", "crafted"],
    icon: "🛋️",
    estimatedTime: "2-4 வாரங்கள்",
    price: "₹10,000 - ₹5,00,000",
  },
  {
    id: "furniture-2",
    category: "Furniture",
    name: "உட்புற வடிவமைப்பு",
    description: "உங்கள் இடத்திற்கான தொழில்முறை வடிவமைப்பு ஆலோசனை",
    keywords: ["interior", "design", "consultation", "decor", "space", "planning", "layout", "aesthetic", "furnishing", "style"],
    icon: "🎨",
    estimatedTime: "1-2 வாரங்கள்",
    price: "₹5,000 - ₹50,000",
  },
  {
    id: "furniture-3",
    category: "Furniture",
    name: "பொருத்துதல் சேவை",
    description: "தொழில்முறையான அசெம்பிள் மற்றும் பொருத்துதல்",
    keywords: ["installation", "assembly", "fitting", "setup", "mount", "fix", "furniture", "service", "professional", "home"],
    icon: "🔩",
    estimatedTime: "2-4 மணிநேரம்",
    price: "₹2,000 - ₹10,000",
  },
  {
    id: "furniture-4",
    category: "Furniture",
    name: "ஹோம் டெலிவரி",
    description: "உங்கள் வீட்டு வாசலுக்கு விரைவான மற்றும் பாதுகாப்பான டெலிவரி",
    keywords: ["delivery", "home delivery", "transport", "shipping", "doorstep", "logistics", "safe", "quick", "furniture", "drop"],
    icon: "🚚",
    estimatedTime: "1-3 நாட்கள்",
    price: "₹500 - ₹5,000",
  },
  {
    id: "furniture-5",
    category: "Furniture",
    name: "டைல்ஸ் பொருத்துதல்",
    description: "குடியிருப்பு மற்றும் வணிக இடங்களுக்கான தொழில்முறையான டைல்ஸ் பொருத்துதல்",
    keywords: ["tile", "tiling", "flooring", "floor", "wall tile", "ceramic", "vitrified", "installation", "bathroom", "kitchen"],
    icon: "🧱",
    estimatedTime: "1-3 நாட்கள்",
    price: "₹2,000 - ₹15,000",
  },

  // Technology Services
  {
    id: "tech-1",
    category: "Technology",
    name: "வலை மேம்பாடு",
    description: "தனிப்பயன் வலைத்தள மேம்பாடு மற்றும் வடிவமைப்பு",
    keywords: ["web", "website", "development", "design", "HTML", "react", "frontend", "backend", "custom", "online"],
    icon: "🌐",
    estimatedTime: "4-12 வாரங்கள்",
    price: "₹50,000 - ₹10,00,000",
  },
  {
    id: "tech-2",
    category: "Technology",
    name: "மொபைல் ஆப் மேம்பாடு",
    description: "iOS மற்றும் ஆண்ட்ராய்டு ஆப் மேம்பாடு",
    keywords: ["mobile", "app", "iOS", "android", "development", "application", "flutter", "react native", "smartphone", "software"],
    icon: "📲",
    estimatedTime: "8-16 வாரங்கள்",
    price: "₹1,00,000 - ₹20,00,000",
  },
  {
    id: "tech-3",
    category: "Technology",
    name: "மென்பொருள் மேம்பாடு",
    description: "வணிகங்களுக்கான தனிப்பயன் மென்பொருள் தீர்வுகள்",
    keywords: ["software", "development", "custom", "business", "application", "coding", "programming", "solution", "enterprise", "system"],
    icon: "💾",
    estimatedTime: "மாறுபடும்",
    price: "₹2,00,000 - ₹50,00,000",
  },
  {
    id: "tech-4",
    category: "Technology",
    name: "ஐடி ஆலோசனை",
    description: "தொழில்நுட்ப உத்தி மற்றும் செயலாக்கம்",
    keywords: ["IT", "consulting", "technology", "strategy", "implementation", "advice", "digital", "transformation", "infrastructure", "expert"],
    icon: "🤝",
    estimatedTime: "தொடரும்",
    price: "₹5,000 - ₹50,000/நாள்",
  },

  // Fabrication Services
  {
    id: "fabrication-1",
    category: "Fabrication",
    name: "UPVC ஜன்னல்கள் & கதவுகள்",
    description: "நவீன தோற்றம் மற்றும் நீடித்துழைப்புடன் கூடிய உயர் தர UPVC ஜன்னல் மற்றும் கதவுப் பொருத்துதல்",
    keywords: ["upvc", "window", "door", "frame", "glass", "fitting", "sliding", "fabrication", "durable", "modern"],
    icon: "🪟",
    estimatedTime: "3-10 நாட்கள்",
    price: "₹15,000 - ₹3,00,000",
  },
  {
    id: "fabrication-2",
    category: "Fabrication",
    name: "கொசு வலை ஜன்னல்கள்",
    description: "பூச்சிகளை வெளியே வைத்திருக்க ஜன்னல்கள் மற்றும் கதவுகளுக்கான தனிப்பயன்-பொருத்தப்பட்ட கொசு வலைத் தீர்வுகள்",
    keywords: ["mosquito", "net", "mesh", "window", "door", "insect", "protection", "custom", "screen", "fitting"],
    icon: "🦟",
    estimatedTime: "1-3 நாட்கள்",
    price: "₹2,000 - ₹25,000",
  },
  {
    id: "fabrication-3",
    category: "Fabrication",
    name: "ஃபேப்ரிகேஷன் வேலைகள்",
    description: "கேட்கள், கிரில்கள், ரெயிலிங்குகள் மற்றும் தனிப்பயன் கட்டமைப்புகள் உள்ளிட்ட அனைத்து வகையான மெட்டல் ஃபேப்ரிகேஷன்கள்",
    keywords: ["fabrication", "metal", "gate", "grill", "railing", "steel", "iron", "welding", "custom", "structure"],
    icon: "🏗️",
    estimatedTime: "3-15 நாட்கள்",
    price: "₹10,000 - ₹5,00,000",
  },
];
